spring.application.name=generador-clientes
spring.jackson.time-zone=America/Mexico_City

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto= validate

spring.datasource.tvch.url=jdbc:mysql://64.23.224.56:3306/tvch
spring.datasource.tvch.username=dev
spring.datasource.tvch.password=Dev-2024
spring.datasource.tvch.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.old.url=jdbc:mysql://localhost:3306/atotonilco
spring.datasource.old.username=root
spring.datasource.old.password=javier2090
spring.datasource.old.driverClassName=com.mysql.cj.jdbc.Driver

tvch.user.id.instalador=2