spring.application.name=generador-clientes
spring.jackson.time-zone=America/Mexico_City

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto= update

spring.datasource.tvch.url=jdbc:mysql://localhost:3306/tvch
spring.datasource.tvch.username=root
spring.datasource.tvch.password=javier2090
spring.datasource.tvch.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.providencia.url=jdbc:mysql://localhost:3306/providencia
spring.datasource.providencia.username=root
spring.datasource.providencia.password=javier2090
spring.datasource.providencia.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.pachuquilla.url=jdbc:mysql://localhost:3306/pachuquilla
spring.datasource.pachuquilla.username=root
spring.datasource.pachuquilla.password=javier2090
spring.datasource.pachuquilla.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.chacon.url=jdbc:mysql://localhost:3306/chacon
spring.datasource.chacon.username=root
spring.datasource.chacon.password=javier2090
spring.datasource.chacon.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.tuzos.url=jdbc:mysql://localhost:3306/tuzos
spring.datasource.tuzos.username=root
spring.datasource.tuzos.password=javier2090
spring.datasource.tuzos.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.avila.url=jdbc:mysql://localhost:3306/avila
spring.datasource.avila.username=root
spring.datasource.avila.password=javier2090
spring.datasource.avila.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.xochihuacan.url=jdbc:mysql://localhost:3306/xochihuacan
spring.datasource.xochihuacan.username=root
spring.datasource.xochihuacan.password=javier2090
spring.datasource.xochihuacan.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.campestre.url=jdbc:mysql://localhost:3306/campestre
spring.datasource.campestre.username=root
spring.datasource.campestre.password=javier2090
spring.datasource.campestre.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.villas.url=jdbc:mysql://localhost:3306/villas
spring.datasource.villas.username=root
spring.datasource.villas.password=javier2090
spring.datasource.villas.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.oncejulio.url=jdbc:mysql://localhost:3306/11julio
spring.datasource.oncejulio.username=root
spring.datasource.oncejulio.password=javier2090
spring.datasource.oncejulio.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.veintenoviembre.url=jdbc:mysql://localhost:3306/20noviembre
spring.datasource.veintenoviembre.username=root
spring.datasource.veintenoviembre.password=javier2090
spring.datasource.veintenoviembre.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.nopancalco.url=jdbc:mysql://localhost:3306/nopancalco
spring.datasource.nopancalco.username=root
spring.datasource.nopancalco.password=javier2090
spring.datasource.nopancalco.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.santajulia.url=jdbc:mysql://localhost:3306/santa_julia
spring.datasource.santajulia.username=root
spring.datasource.santajulia.password=javier2090
spring.datasource.santajulia.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.piracantos.url=jdbc:mysql://localhost:3306/piracantos
spring.datasource.piracantos.username=root
spring.datasource.piracantos.password=javier2090
spring.datasource.piracantos.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.sancayetano.url=jdbc:mysql://localhost:3306/san_cayetano
spring.datasource.sancayetano.username=root
spring.datasource.sancayetano.password=javier2090
spring.datasource.sancayetano.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.tepeyahualco.url=jdbc:mysql://localhost:3306/tepeyahualco
spring.datasource.tepeyahualco.username=root
spring.datasource.tepeyahualco.password=javier2090
spring.datasource.tepeyahualco.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.tlanalapa.url=jdbc:mysql://localhost:3306/tlanalapa
spring.datasource.tlanalapa.username=root
spring.datasource.tlanalapa.password=javier2090
spring.datasource.tlanalapa.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.sahagun.url=jdbc:mysql://localhost:3306/sahagun
spring.datasource.sahagun.username=root
spring.datasource.sahagun.password=javier2090
spring.datasource.sahagun.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.apan.url=jdbc:mysql://localhost:3306/apan
spring.datasource.apan.username=root
spring.datasource.apan.password=javier2090
spring.datasource.apan.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.tepeapulco.url=jdbc:mysql://localhost:3306/tepeapulco
spring.datasource.tepeapulco.username=root
spring.datasource.tepeapulco.password=javier2090
spring.datasource.tepeapulco.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.chimalpa.url=jdbc:mysql://localhost:3306/chimalpa
spring.datasource.chimalpa.username=root
spring.datasource.chimalpa.password=javier2090
spring.datasource.chimalpa.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.lazaro.url=jdbc:mysql://localhost:3306/lazaro
spring.datasource.lazaro.username=root
spring.datasource.lazaro.password=javier2090
spring.datasource.lazaro.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.santaclara.url=jdbc:mysql://localhost:3306/santa_clara
spring.datasource.santaclara.username=root
spring.datasource.santaclara.password=javier2090
spring.datasource.santaclara.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.irolo.url=jdbc:mysql://localhost:3306/irolo
spring.datasource.irolo.username=root
spring.datasource.irolo.password=javier2090
spring.datasource.irolo.driverClassName=com.mysql.cj.jdbc.Driver

#spring.datasource.acopinalco.url=jdbc:mysql://localhost:3306/acopinalco
#spring.datasource.acopinalco.username=root
#spring.datasource.acopinalco.password=javier2090
#spring.datasource.acopinalco.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.emiliano.url=jdbc:mysql://localhost:3306/emiliano
spring.datasource.emiliano.username=root
spring.datasource.emiliano.password=javier2090
spring.datasource.emiliano.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.almoloya.url=jdbc:mysql://localhost:3306/almoloya
spring.datasource.almoloya.username=root
spring.datasource.almoloya.password=javier2090
spring.datasource.almoloya.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.union.url=jdbc:mysql://localhost:3306/union
spring.datasource.union.username=root
spring.datasource.union.password=javier2090
spring.datasource.union.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.real.url=jdbc:mysql://localhost:3306/real
spring.datasource.real.username=root
spring.datasource.real.password=javier2090
spring.datasource.real.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.omitlan.url=jdbc:mysql://localhost:3306/omitlan
spring.datasource.omitlan.username=root
spring.datasource.omitlan.password=javier2090
spring.datasource.omitlan.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.atotonilco.url=jdbc:mysql://localhost:3306/atotonilco
spring.datasource.atotonilco.username=root
spring.datasource.atotonilco.password=javier2090
spring.datasource.atotonilco.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.tuxpan.url=jdbc:mysql://localhost:3306/tuxpan
spring.datasource.tuxpan.username=root
spring.datasource.tuxpan.password=javier2090
spring.datasource.tuxpan.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.epazoyucan.url=jdbc:mysql://localhost:3306/epazoyucan
spring.datasource.epazoyucan.username=root
spring.datasource.epazoyucan.password=javier2090
spring.datasource.epazoyucan.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.sanjuan.url=jdbc:mysql://localhost:3306/san_juan
spring.datasource.sanjuan.username=root
spring.datasource.sanjuan.password=javier2090
spring.datasource.sanjuan.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.ahuazotepec.url=jdbc:mysql://localhost:3306/ahuazotepec
spring.datasource.ahuazotepec.username=root
spring.datasource.ahuazotepec.password=javier2090
spring.datasource.ahuazotepec.driverClassName=com.mysql.cj.jdbc.Driver